name: travel-advisory-scrape

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  travel-advisory:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run scraper
      env:
        IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
      run: python travel-advisory.py
